redirectsOrigin = "config"
plugins = []
functionsDirectory = "/home/project_great_escape/.openclaw/workspace/dashboard-app/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/project_great_escape/.openclaw/workspace/dashboard-app/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/home/project_great_escape/.openclaw/workspace/dashboard-app/netlify/functions"

[build.environment]
VITE_API_URL = "https://forge-backend--xavierhofer.replit.app"
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]